server.port=8080

# Base de datos — valores vienen de variables de entorno de Azure
spring.datasource.url=${AZURE_MYSQL_URL}
spring.datasource.username=${AZURE_MYSQL_USER}
spring.datasource.password=${AZURE_MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=28800000

# CORS — URL real del frontend en Azure
frontend.url=${FRONTEND_URL}

# Uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
upload.dir=/home/uploads/

# Logs
logging.file.name=/home/logs/app.log
logging.level.root=INFO
logging.level.com.ventas=WARN